// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Unigis.Api.Data;

#nullable disable

namespace Unigis.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250818190847_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Unigis.Api.Models.PuntoVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<decimal>("Latitud")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("Longitud")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("Venta")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Zona")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("PuntosVenta");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Sucursal Centro",
                            Latitud = 19.432608m,
                            Longitud = -99.133209m,
                            Venta = 12000m,
                            Zona = "Centro"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Sucursal Sur",
                            Latitud = 19.36m,
                            Longitud = -99.18m,
                            Venta = 8000m,
                            Zona = "Sur"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Sucursal Norte",
                            Latitud = 19.50m,
                            Longitud = -99.10m,
                            Venta = 15000m,
                            Zona = "Norte"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
